# Generated by Django 4.1.3 on 2022-12-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('pc', 'pc'), ('mobile', 'mobile'), ('notebook', 'notebook')], default='mobile', max_length=20),
        ),
    ]
