# Generated by Django 4.1.3 on 2022-12-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('mobile', 'mobile'), ('pc', 'pc'), ('notebook', 'notebook')], default='mobile', max_length=20),
        ),
    ]
