# Generated by Django 4.1.3 on 2022-12-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_product_group_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
